/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include "Reg_Macros.h"
#include "RCC.h"
#include "Gpio.h"

int main(void)
{
	//RCC_AHB1PeripheralClkEnable(EN_GPIOA);
	Port_Init (&Port_Config0);

#if 0
	RCC_AHB1PeripheralClkEnable(EN_GPIOD);
	GPIO_D.MODER.B.ModeR1 = 0x1U;
	GPIO_D.MODER.R = (0x1U<<2U);

	if((GPIO_B.MODER.B.ModeR1)==0x1U)
	{
		RCC_AHB1PeripheralClkEnable(EN_GPIOC);
	}
#endif
	for(;;);
}
